using System.IO;
using System.Text;
using WikiTool;
using WikiTool.Wikis;
using Xunit;

namespace WikiTool.Tests;

public class WikidpadWikiTests
{
    private readonly string _testDir;
    private readonly string _dataDir;

    public WikidpadWikiTests()
    {
        _testDir = TestUtilities.GetTestFolder("wikidpad_wiki_tests");
        _dataDir = Path.Combine(_testDir, "data");
    }


    [Fact]
    public void Constructor_UsesRootWhenNoDataDir()
    {
        //arrange
        if (!Directory.Exists(_testDir))
        {
            Directory.CreateDirectory(_testDir);
        }
        if (Directory.Exists(_dataDir))
        {
            Directory.Delete(_dataDir, true);
        }
        var expected = _testDir;
        var sut = new WikidpadWiki(_testDir);
        //actual
        var actual = sut.DataDir;

        //assert
        Assert.Equal(expected, actual);

    }

    [Fact]
    public void Constructor_FindsDataDirWhenExists()
    {
        //arrange
        Directory.CreateDirectory(_dataDir);
        var expected = _dataDir;
        var sut = new WikidpadWiki(_testDir);
        //actual
        var actual = sut.DataDir;

        //assert
        Assert.Equal(expected, actual);

    }



    [Fact]
    public void Constructor_LoadsAllPages()
    {
        Directory.CreateDirectory(_dataDir);
        //arrange
        File.WriteAllText(Path.Combine(_dataDir, @"TestOne.wiki"), string.Empty);
        File.WriteAllText(Path.Combine(_dataDir, @"TestTwo.wiki"), string.Empty);
        //actual
        var sut = new WikidpadWiki(_testDir);
        var pageList = sut.GetAllPages();

        //assert
        Assert.Equal("TestOne", pageList[0].Name);
        Assert.Equal("TestTwo", pageList[1].Name);

    }
        
    [Fact]
    public void GetPageContent_GetsContentAndMarksPageAsRead()
    {
        Directory.CreateDirectory(_dataDir);
        //arrange
        var expected = "+ Test One\n\n-This wiki file is generated by tests\n[tag:tests]";
        var expected2 = "+ Test Two\n\n-This wiki file is generated by tests\n[tag:tests] CategoryTests";
        File.WriteAllText(Path.Combine(_dataDir, "TestOne.wiki"), expected);
        File.WriteAllText(Path.Combine(_dataDir, "TestTwo.wiki"), expected2);
        //actual
        var sut = new WikidpadWiki(_testDir);
        var pageList = sut.GetAllPages();

        //assert
        Assert.Equal(expected, pageList[0].GetContent());
        Assert.Equal(expected2, pageList[1].GetContent());

        Assert.False(pageList[0].ContentIsStale);
        Assert.False(pageList[1].ContentIsStale);


    }

    [Fact]
    public void GetPagesBySearchStr_ReturnsOnlyMatchingPages()
    {
        Directory.CreateDirectory(_dataDir);
        //arrange
        File.WriteAllText(Path.Combine(_dataDir, "TestOne.wiki"), "+ Test One\n\nthis page has a needle in it");
        File.WriteAllText(Path.Combine(_dataDir, "TestTwo.wiki"), "+ Test Two\n\nnothing to find here");
        var sut = new WikidpadWiki(_testDir);

        //actual
        var result = sut.GetPagesBySearchStr("needle");

        //assert
        Assert.Single(result);
        Assert.Equal("TestOne", result[0].Name);
    }

    [Fact]
    public void GetPagesBySearchStr_PopulatesSelectedPages()
    {
        Directory.CreateDirectory(_dataDir);
        //arrange
        File.WriteAllText(Path.Combine(_dataDir, "TestOne.wiki"), "this page has a needle in it");
        File.WriteAllText(Path.Combine(_dataDir, "TestTwo.wiki"), "nothing to find here");
        var sut = new WikidpadWiki(_testDir);

        //actual
        sut.GetPagesBySearchStr("needle");

        //assert
        Assert.Single(sut.SelectedPages);
        Assert.Equal("TestOne", sut.SelectedPages[0].Name);
    }

    [Fact]
    public void GetPagesBySearchStr_ReturnsEmptyWhenNoMatches()
    {
        Directory.CreateDirectory(_dataDir);
        //arrange
        File.WriteAllText(Path.Combine(_dataDir, "TestOne.wiki"), "nothing to find here");
        var sut = new WikidpadWiki(_testDir);

        //actual
        var result = sut.GetPagesBySearchStr("needle");

        //assert
        Assert.Empty(result);
    }
}